version: '3.8'

services:
  matiasduranapi:
    container_name: matiasduranapi
    depends_on:
      - mysqldb
    build: 
      context: ./matiasduranapi/src
      dockerfile: prod.Dockerfile
    restart: always
    env_file: ./matiasduranapi/src/.env
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matiasduranapi.rule=Host(`api.matiasduran.site`)"
      - "traefik.http.services.matiasduranapi.loadbalancer.server.port=5000"
      - "traefik.http.routers.matiasduranapi.entrypoints=websecure"  # Asegura HTTPS
      - "traefik.http.routers.matiasduranapi.tls.certresolver=cloudflare"  # Resolver TLSs
    stdin_open: true
    tty: true
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    env_file: ./matiasduranapi/src/.env
    networks:
      - my_network
    environment:
      - MYSQL_ROOT_PASSWORD=demo_pass
      - MYSQL_DATABASE=demo_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./matiasduranapi/src/db_dumps:/docker-entrypoint-initdb.d

networks:
  my_network:
    external: true


volumes:
  db: